version: '3'

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - kestra-network

  kestra:
    image: kestra/kestra:latest
    ports:
      - "8080:8080"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: server local
    networks:
      - kestra-network

networks:
  kestra-network:
    driver: bridge
